### ISSUE TITLE
the plugin wants to restart on each reboot

### ISSUE THREAD

**Issue by Clem1470** [NewAmazingPVP/AutoUpdateGeyser#5]
![Capture](https://github.com/NewAmazingPVP/AutoUpdateGeyser/assets/88685864/e2e69d9e-40ee-46bd-b3b6-d8d12a7ca907)

the consol says it's a first for Geyser. But it's not.
But the plugin works with floodgate.

**Comment by NewAmazingPVP** [comment]
@Clem1470 What platform are you using? Seems like it does detect the latest build 410 but seems like it's not installing it? Are you sure you deleted all builds of geyser and floodgate before installing the plugin? If not it might be conflicting with another installation of geyser.

**Comment by NewAmazingPVP** [comment]
Sorry I see you are using spigot and I think I found the bug in the code. Instead of Geyser-Spigot it's trying to find Geyser-spigot which since it's case sensitive it cannot be found. I'll fix this soon thanks for informing me.

**Comment by NewAmazingPVP** [comment]
@Clem1470 Hey there I am not able to recreate this issue seems to be working fine with me. Can you please send your config.yml and are you sure you have the latest release downloaded from spigot?

**Comment by NewAmazingPVP** [comment]
@Clem1470 Try the new build I just released and let me know if that works https://github.com/NewAmazingPVP/AutoUpdateGeyser/releases/download/v4.0/AutoUpdateGeyser-4.0.jar

**Comment by Clem1470** [comment]
@NewAmazingPVP Thank you very much, the update works fine. Thank you for your speed

**Comment by NewAmazingPVP** [comment]
Alright perfect!
